### ISSUE TITLE
[Bug] Backslash (\) not escaped

### ISSUE THREAD

**Issue by alex5imon** [KanoComputing/make-snake#55]
If the inputted commands contain a backslash () character, then the line is not immediately parsed and a new, blank line is shown. This can be confusing as it makes the user think that the program has crashed or they need to input more when actually they have already got the command wrong.

```
python snake \
```
Won't run the command

**Comment by cwilson-github** [comment]
The make-snake file that I modified will fix this issue.

**Comment by alex5imon** [comment]
@cwilson-github the PR has been tested and the problem is fixed. Thanks for your contribution!

I would like to add you as contributor, what name would you like me to use?

**Comment by cwilson-github** [comment]
You can use https://github.com/cwilson-github
